HenriPizza/Models/OrderSummary.cs
using HenriPizza.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HenriPizza.Models
{
    public class OrderSummary
    {
        [Key]
        public int OrderSummaryId { get; set; }

        public int UserId { get; set; }

        public string OrderDate { get; set; }

        public string OrderAddress { get; set; }

        public string Note { get; set; }

        public decimal TotalPrice { get; set; }

        public string State { get; set; }

        public ICollection<OrderItem> OrderItems { get; set; }

        public User User { get; set; }
    }
}

HenriPizza/Controllers/OrderSummariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HenriPizza.Models;

namespace HenriPizza.Controllers
{
    public class OrderSummariesController : Controller
    {
        private DBContext db = new DBContext();

        // GET: OrderSummaries
        [Authorize (Roles = "Admin")]
        public ActionResult Index()
        {
            var orderSummaries = db.OrderSummaries.Include(o => o.User);
            return View(orderSummaries.ToList());
        }

        // GET: OrderSummaries/Details/5
        [Authorize]
        public ActionResult Details()
        {
            int userId = Convert.ToInt32(HttpContext.User.Identity.Name);
            OrderSummary orderId = db.OrderSummaries.Where(o => o.UserId == userId && o.State == "Non Evaso").FirstOrDefault();
            
            OrderSummary orderSummary = db.OrderSummaries
                                          .Include(o => o.OrderItems)
                                          .Include(o => o.OrderItems.Select(i => i.Product))
                                          .SingleOrDefault(o => o.OrderSummaryId == orderId.OrderSummaryId);

            if (orderSummary != null)
            {
            ViewBag.TotalPrice = orderSummary.OrderItems?.Sum(item => item.ItemPrice) ?? 0;
            return View(orderSummary);
            }
            else
            {
                return View();
            }

            
        }

        // GET: OrderSummaries/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email");
            return View();
        }

        // POST: OrderSummaries/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "OrderSummaryId,UserId,OrderDate,OrderAddress,Note,TotalPrice,State")] OrderSummary orderSummary)
        {
            if (ModelState.IsValid)
            {
                db.OrderSummaries.Add(orderSummary);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", orderSummary.UserId);
            return View(orderSummary);
        }

        // GET: OrderSummaries/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderSummary orderSummary = db.OrderSummaries.Find(id);
            if (orderSummary == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", orderSummary.UserId);
            return View(orderSummary);
        }

        // POST: OrderSummaries/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "OrderSummaryId,UserId,OrderDate,OrderAddress,Note,TotalPrice,State")] OrderSummary orderSummary)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderSummary).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", orderSummary.UserId);
            return View(orderSummary);
        }

        // GET: OrderSummaries/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderSummary orderSummary = db.OrderSummaries.Find(id);
            if (orderSummary == null)
            {
                return HttpNotFound();
            }
            return View(orderSummary);
        }

        // POST: OrderSummaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderSummary orderSummary = db.OrderSummaries.Find(id);
            db.OrderSummaries.Remove(orderSummary);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmOrder(int id, string OrderAddress, string Note)
        {
            if (id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderSummary orderSummary = db.OrderSummaries.Where(o => o.OrderSummaryId == id).FirstOrDefault();
            if (orderSummary == null)
            {
                return HttpNotFound();
            }
            decimal PrezzoTotale = db.OrderItems
                         .Where(o => o.OrderSummaryId == id)
                         .Sum(item => item.ItemPrice);
            if (ModelState.IsValid)
            {
                orderSummary.OrderDate = DateTime.Now.ToString();
                orderSummary.State = "Evaso";
                orderSummary.OrderAddress = OrderAddress;
                orderSummary.Note = Note;
                orderSummary.TotalPrice = PrezzoTotale;

                db.Entry(orderSummary).State = EntityState.Modified;
                db.SaveChanges();

                TempData["SuccessMessage"] = true;
                return RedirectToAction("Index", "Home");
            }

            
            return View("Details", orderSummary);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteItem(int itemId)
        {
            OrderItem item = db.OrderItems.Find(itemId);
            if (item != null)
            {
                int orderSummaryId = item.OrderSummaryId;
                db.OrderItems.Remove(item);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = orderSummaryId });
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult OrdiniEvasi()
        {
            var ordiniEvasi = db.OrderSummaries.Where(o => o.State == "Evaso").Count();
                
            return Json(ordiniEvasi, JsonRequestBehavior.AllowGet);

        }

        [Authorize(Roles = "Admin")]
        public ActionResult IncassiPerGiorno(int id)
        {
            var ordiniTot = db.OrderSummaries.Where(o => o.State == "Evaso").ToList();
            decimal incassoGiornaliero = 0;
            foreach (var order in ordiniTot)
            {
                if (order.OrderDate != null) 
                {
                    string date = order.OrderDate.ToString();
                    string[] arrayData = date.Split('/');
                    int day = Convert.ToInt32(arrayData[0]);
                    if (day == id)
                    {
                        incassoGiornaliero += order.TotalPrice;
                    }
                }
            }

            return Json(incassoGiornaliero, JsonRequestBehavior.AllowGet);
        }


        [Authorize(Roles = "Admin")]
        public ActionResult Statistiche()
        {
            return View();
        }

    }
}

HenriPizza/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HenriPizza.Models;

namespace HenriPizza.Controllers
{
    public class ProductsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Products
        [Authorize]
        public ActionResult Index()
        {
            LinkCarrello();
            
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                return View(db.Products.ToList());
            }
            else
            {
                return View("Vetrina", db.Products.ToList());
            }
        }

        // GET: Products/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            LinkCarrello();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            LinkCarrello();
            return View();
        }

        // POST: Products/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductName,ProductImage,ProductPrice,PreparationTime,Ingredients,Category")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles ="Admin")]
        public ActionResult Edit(int? id)
        {
            LinkCarrello();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductName,ProductImage,ProductPrice,PreparationTime,Ingredients,Category")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [Authorize]
        public ActionResult VetrinaDetails(int? id)
        {
            LinkCarrello();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles ="Admin")]
        public ActionResult Delete(int? id)
        {
            LinkCarrello();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [Authorize(Roles ="Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public void LinkCarrello()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                int userId = Convert.ToInt32(HttpContext.User.Identity.Name);
                using (DBContext db = new DBContext())
                {
                    OrderSummary Carrello = db.OrderSummaries.Where(c => c.UserId == userId && c.State == "Non Evaso").FirstOrDefault();
                    if (Carrello == null)
                    {
                        OrderSummary newOrder = new OrderSummary
                        {
                            UserId = userId,
                            State = "Non Evaso"
                        };
                        db.OrderSummaries.Add(newOrder);
                        db.SaveChanges();

                    }
                    
                }
            }
        }
    }
}

HenriPizza/Views/OrderSummaries/Create.cshtml
@model HenriPizza.Models.OrderSummary

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrderSummary</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HenriPizza/Views/OrderSummaries/Delete.cshtml
@model HenriPizza.Models.OrderSummary

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderSummary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HenriPizza/Views/OrderSummaries/Details.cshtml
@model HenriPizza.Models.OrderSummary

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Dettagli Ordine";
}

<div class="container mt-5">
    <h4>Dettagli Ordine</h4>

    @if (Model.OrderItems.Any() && Model.OrderItems.Sum(item => item.ItemPrice * item.Quantity) > 0)
    {
        foreach (var item in Model.OrderItems)
        {
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="@Url.Content(item.Product.ProductImage)" class="card-img" alt="Immagine del Prodotto">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">@item.Product.ProductName</h5>
                            <p class="card-text">Prezzo per unità: @item.Product.ProductPrice €</p>
                            <p class="card-text">Quantità: @item.Quantity</p>
                            <p class="card-text">Subtotale: @(item.ItemPrice * item.Quantity) €</p>
                            @using (Html.BeginForm("DeleteItem", "OrderSummaries", new { itemId = item.OrderItemId }, FormMethod.Post, new { @class = "d-inline" }))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-danger">Elimina</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }

        <div class="card">
            <div class="card-header">
                Informazioni Ordine
            </div>
            <div class="card-body">
                <p class="card-text"><strong>Totale Ordine:</strong> @Model.OrderItems.Sum(item => item.ItemPrice * item.Quantity) €</p>
            </div>
        </div>

        if (Model.State != "Evaso")
        {
            using (Html.BeginForm("ConfirmOrder", "OrderSummaries", new { id = Model.OrderSummaryId }, FormMethod.Post, new { @class = "mt-3" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label for="OrderAddress">Indirizzo di Consegna:</label>
                     @Html.TextBoxFor(m => m.OrderAddress, new { @class = "form-control", id = "OrderAddress" })

                </div>
                <div class="form-group">
                    <label for="Note">Note:</label>
                    @Html.TextAreaFor(m => m.Note, new { @class = "form-control", rows = "3", id = "Note", placeholder = "Inserisci intolleranze e/o specifica l'orario di consegna dell'ordine" })
                </div>
                <button type="submit" class="btn btn-success mt-3">Conferma Ordine</button>
            }
        }
    }
    else
    {
        <div class="text-center">
            <h3>Il tuo carrello è vuoto</h3>
            <p>Visita la nostra pagina dei prodotti per aggiungere articoli al tuo carrello.</p>
            <a href="@Url.Action("Index", "Products")" class="btn btn-primary">Visita Prodotti</a>
        </div>
    }
</div>

HenriPizza/Views/OrderSummaries/Edit.cshtml
@model HenriPizza.Models.OrderSummary

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrderSummary</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderSummaryId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HenriPizza/Views/OrderSummaries/Index.cshtml
@model IEnumerable<HenriPizza.Models.OrderSummary>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OrderSummaryId }) |
            @Html.ActionLink("Details", "Details", new { id=item.OrderSummaryId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OrderSummaryId })
        </td>
    </tr>
}

</table>

HenriPizza/Views/OrderSummaries/Statistiche.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Statistiche Ordini";
}

<h2>Statistiche Ordini</h2>

<div class="container">
    <!-- Incassi per giorno -->
    <div class="row mb-3">
        <div class="col">
            <h4>Incassi per giorno:</h4>
            <select id="giorniSelect" class="form-control">
                @for (int i = 1; i <= 31; i++)
                {
                    <option value="@i">@i</option>
                }
            </select>
            <button id="fetchIncassi" class="btn btn-primary mt-2">Mostra Incassi</button>
            <div id="incassiRisultato" class="mt-2"></div>
        </div>
    </div>

    <!-- Ordini Evasi -->
    <div class="row">
        <div class="col">
            <h4>Ordini Evasi:</h4>
            <button id="fetchOrdiniEvasi" class="btn btn-primary">Mostra Ordini Evasi</button>
            <div id="ordiniEvasiRisultato" class="mt-2"></div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    <script>
        $(document).ready(function () {
            $("#fetchIncassi").click(function () {
                var giornoSelezionato = $('#giorniSelect').val();
                $.ajax({
                    url: '@Url.Action("IncassiPerGiorno", "OrderSummaries")/' + giornoSelezionato,
                    type: 'GET',
                    success: function (result) {
                        $("#incassiRisultato").html("Incasso giornaliero: €" + result);
                    },
                    error: function (xhr, status, error) {
                        $("#incassiRisultato").html("Errore nel recupero degli incassi.");
                    }
                });
            });

            $("#fetchOrdiniEvasi").click(function () {
                $.ajax({
                    url: '@Url.Action("OrdiniEvasi", "OrderSummaries")',
                    type: 'GET',
                    success: function (result) {
                        $("#ordiniEvasiRisultato").html("Numero ordini evasi: " + result);
                    },
                    error: function (xhr, status, error) {
                        $("#ordiniEvasiRisultato").html("Errore nel recupero degli ordini evasi.");
                    }
                });
            });
        });
    </script>
}